name: waterspring
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  http: ^1.0.0
  shared_preferences: ^2.1.2
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  curved_navigation_bar: ^1.0.3
  intl: ^0.18.1
  sliding_up_panel: ^2.0.0+1
  flutter_map: ^5.0.0
  flutter_map_line_editor: ^5.0.0
  cached_network_image: ^3.2.3
  latlong2: ^0.9.0
  # flutter_map_dragmarker: ^5.0.0
 
  google_fonts:
  flutter_svg:
  provider:
  multi_select_flutter: ^4.1.3
  flutter_map_dragmarker: ^5.0.0
  get: ^4.6.5
  velocity_x: ^4.1.1
  flutter_map_marker_popup: ^5.2.0
  # url_launcher: ^6.1.14
  # webview_flutter: ^4.4.1
  # dropdown_button3: ^3.0.0
  # turf: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/icons/
    - assets/weather/